allow users to switch between login prompt versions
rex706/SAM pull request #157
Opened 2022-10-24 12:51 UTC by KillaBoi

Valve has fixed command line options in the latest stable release of the Steam Client.

This PR allows the user to switch between the React based Steam Login UI Prompt (therefore allowing the user to easily login without having to enter a Steam Guard code by "approving" the login) or to alternatively switch back to the old non React based login prompt by the usage of a parameter checkbox.

2022-10-24 13:02 UTC, KillaBoi commented
this actually breaks automated sign-in via the automatic input of the shared secret steam guard codes for the new ui, we will need to look into that...

2022-11-19 17:36 UTC, PindaPixel commented
> this actually breaks automated sign-in via the automatic input of the shared secret steam guard codes for the new react UI, we will need to look into that...

Patch note from today:
> Fixed an input focus bug requiring an initial click on the sign in UI before you could type your username or password

This the fix you needed?

2022-11-22 23:45 UTC, KillaBoi commented
just tested, can confirm that patch note does indeed fix the input bug we had.

@rex706, can we accept the PR whenever possible and go ahead and push/make it global? :)

2022-11-23 19:23 UTC, rex706 requested changes

2022-11-23 19:23 UTC, rex706 commented on Core/Utils.cs
> +
Probably don't need all these extra spaces here.

2022-11-23 19:23 UTC, rex706 commented on Views/SettingsWindow.xaml.cs
> +
Is all this duplicate?

2022-11-23 19:23 UTC, rex706 commented on Core/Utils.cs
> +using ControlzEx.Standard;
Do we need this in Utils.cs?

2022-11-23 19:23 UTC, rex706 commented on Core/Utils.cs
> +        public const int WM_LBUTTONDOWN = 0x0201;
We can get rid of these for now since they aren't being used.

2022-11-23 19:28 UTC, rex706 requested changes

2022-11-23 19:28 UTC, rex706 commented on Core/Utils.cs
> +        public const int WM_LBUTTONUP = 0x0202;
We can get rid of these for now since they are not being used.

2022-11-23 19:28 UTC, rex706 commented on Core/Utils.cs
> +
Probably don't need all these extra spaces here.

2022-11-23 19:28 UTC, rex706 commented on Views/SettingsWindow.xaml.cs
> +                CustomParametersTextBox.Text = settings.File.Read(SAMSettings.CUSTOM_PARAMETERS_VALUE, SAMSettings.SECTION_PARAMETERS);
Is this all duplicate?

2022-11-23 21:01 UTC, KillaBoi commented
it seems that it is still somehow broken, not sure how or why but after the update something broke with the input where it will either accept it or not accept it

2022-11-23 22:19 UTC, rex706 requested changes

2022-11-23 22:19 UTC, rex706 commented on Views/AccountsWindow.xaml.cs
> +            Core.Utils.SendTab(steamLoginWindow.RawPtr, settings.User.VirtualInputMethod);
I'm not so sure we need to do this.

2022-11-28 17:45 UTC, rex706 commented
Unfortunately, there was more work required to get the new UI working while also preserving the old functionality as well that I implemented, so I'm closing this request. 

I very much appreciate your help with getting this moving quickly.

2022-11-28 17:45 UTC, closed without merging